// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU0r16swxKFctrQhY7jcI-CmnCorqLA8Q',
    appId: '1:196130122544:android:788b9775a81b90cc4036f5',
    messagingSenderId: '196130122544',
    projectId: 'pcclince',
    storageBucket: 'pcclince.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2IcM2DANFU5hpHftutVatqd1rj9ytw9k',
    appId: '1:196130122544:ios:7e7ae82ab09d1f864036f5',
    messagingSenderId: '196130122544',
    projectId: 'pcclince',
    storageBucket: 'pcclince.firebasestorage.app',
    iosBundleId: 'com.maf99.pcclinc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoyzW5vO5B8Gog_SZxeJlDSbd_cilDdyM',
    appId: '1:196130122544:web:a87533ee2282638c4036f5',
    messagingSenderId: '196130122544',
    projectId: 'pcclince',
    authDomain: 'pcclince.firebaseapp.com',
    storageBucket: 'pcclince.firebasestorage.app',
    measurementId: 'G-PE9FM4Y85R',
  );
}
